### ISSUE TITLE
ResultSummary node does not exist in the RPC Response XML tree

### ISSUE THREAD

**Issue by mirceaulinic** [fooelisa/pyiosxr#12]
Hello,

I have noticed that there is a issue when trying to make a simple RPC call to a IOS-XR device (version 5.3.1):

> > > device.make_rpc_call('<Get><Operational><Interfaces><InterfaceTable></InterfaceTable></Interfaces></Operational></Get>')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 119, in make_rpc_call
> > >     result = **execute_rpc**(self.device, rpc_command, self.timeout)
> > >   File "/usr/local/lib/python2.7/dist-packages/pyIOSXR/iosxr.py", line 42, in **execute_rpc**
> > >     if int(root.find('ResultSummary').get('ErrorCount')) > 0:
> > > AttributeError: 'NoneType' object has no attribute 'get'

The problem is that in the XML Response tree (on IOS-XR 5.3.1 at least), the node ResultSummary does not exist thus the second get fails since the first get returns None object.

**Comment by mirceaulinic** [comment]
RPC command below (not displayed previously):

```
<Get><Operational><NTP><NodeTable></NodeTable></NTP></Operational></Get>
```

**Comment by jejenone** [comment]
ResultSummary exists, but because the library does not support IteratorID, it never gets to the end of the request.
Adding support for IteratorID will fix this problem and many others:
http://www.cisco.com/c/en/us/td/docs/ios_xr_sw/iosxr_r4-1/xml/programming/guide/xl41apidoc/xl41iter.html

adding `iteration off` to the config also fixes the issue.

**Comment by fooelisa** [comment]
Workaround added with #14. Closing this issue
